### ISSUE TITLE
Address webviz-ert feedback

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#243]
Following text is a compiled list of **all** wishes/comments gathered from users without filtering. Many of the issues is probably low-hanging fruits which could be fixed quite easy, some needs more discussion, some is impossible to fix and some is probably issues we won't fix.

### Todo
- [x] #245
- [x] #246
- [x] #247
- [x] #248
- [x] #249
- [x] #250
- [x] #251
- [x] #252
- [ ] #267
- [ ] #269
- [x] #244 
- [ ] #253
- [x] #268
- [x] #254
- [ ] #285

### Discuss
- [ ] #286
- [ ] Grouping of parameters/observations for analysis _new feature_, _needs clarification_, _check with lars_
- [ ]  Observation analyzer
It is getting there - we would like to see them all together, to evaluate which ones are important, and which ones that dont contribute to the objective function. I could give it a go to show them what I mean at some point. Webviz has some good plots on this - it would be great to get some of them in ERT. Parameter-observation analyzer in Webviz: [https://equinor.github.io/webviz-subsurface/#/webviz-subsurface?id=parameteranalysis](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequinor.github.io%2Fwebviz-subsurface%2F%23%2Fwebviz-subsurface%3Fid%3Dparameteranalysis&data=05%7C01%7Cooh%40equinor.com%7C25ed8e8ba60e4eac3a0a08da2cf12dda%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C637871711601490564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EK6Xu3ASeaO%2BMZaxyQSEppvZCs8szViRsV%2Bi6%2B0e%2F0w%3D&reserved=0)
_new feature_, _discuss with lars_, _todo_ 

### Wait
- [ ] Better labeling of x/y axis and labels for color coding (eg when there are colors for different ensembles) _new feature_, _wait_ 
- [ ] Ensemble selection carries over between different plugins _new feature_, _wait_ 
- [ ] The color scheme should be easily modified and controlled by the user _new feature_, _wait_ 
- [ ] Get DESIGN_KW parameters available on equal terms as GEN_KW _new feature_, _epic_
- [ ] All webviz "pages" available in Webviz-ERT _new feature_, _not actionable_ 
- [ ] Build you own Webviz-ERT templates to be used across models and fields (and personel) _new feature_, _needs clarification_ 

User input
Revert single selection of responses in response correlation viewer
Toggle legends disappears
Titles in plot viewer
Toggle observations in respojnse correlation viewer
Sorting order parameters - customizable. ( correlation strong -> weak / alphabetically )

**Comment by oysteoh** [comment]
Remaining issues after our milestone gathered here https://github.com/equinor/webviz-ert/issues/382
